default:
  image: maven:3.8-openjdk-11
  
before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mvn package -Dmaven.test.skip
  artifacts:
    paths:
      - target/*.jar

test:
  image: markhobson/maven-chrome:jdk-11
  needs: [build]
  stage: test
  script:
    - mvn surefire-report:report site -DgenerateReports=false
  artifacts:
    paths:
      - "target/site"
    expire_in: 30 days

staging:
  image: markhobson/maven-chrome:jdk-11
  needs: [test]
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api_key=$HEROKU_API_KEY
    - SPRING_PROFILES_ACTIVE='staging' HOST='https://${HEROKU_APP_STAGING}.herokuapp.com' mvn clean test


production:
  stage: deploy
  needs: [test]
  when: manual
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api_key=$HEROKU_API_KEY
  only:
  - main


