# global configurations
default:
  image: markhobson/maven-chrome:jdk-11

stages:
  - clean
  - build
  - test


clean-job:
  stage: clean
  script:
    - mvn clean

build-job:
  stage: build
  script:
    - mvn package -Dmaven.test.skip
  artifacts:
    paths:
      - target/*.jar

test-job:
  stage: test
  script:
    - mvn test

