default:
  image: maven:3.8-openjdk-11
  
before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mvn package -Dmaven.test.skip
  artifacts:
    paths:
      - target/*.jar

test:
  image: markhobson/maven-chrome:jdk-11
  stage: test
  script:
    - mvn test


staging:
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api_key=$HEROKU_API_KEY
  
production:
  stage: deploy
  when: manual
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api_key=$HEROKU_API_KEY
  only:
  - master


