default:
  image: markhobson/maven-chrome:jdk-11

stages:
  - build
  - test
  - deploy

build job:
  stage: build
  script:
    - mvn package -Dmaven.test.skip
  artifacts:
    paths:
      - target/*.jar

test job:
  stage: test
  script:
    - mvn test

deploy job:
  stage: deploy
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/admin-lte2.git
    - git push -f heroku HEAD:master
    - echo “Deployed to Server https://admin-lte2.herokuapp.com/"
  environment:
    name: staging
    url: https://admin-lte2.herokuapp.com/
  only:
    - master