version: '3'
services:
  mysql_db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=spring_adminlte
    ports:
      - "3306:3306"
    volumes:
      - spring_adminlte_mysql_db:/var/lib/mysql

  postgres_db:
    image: postgres
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=spring_adminlte
    ports:
      - "5432:5432"
    volumes:
      - spring_adminlte_postgresql_db:/var/lib/postgresql/data/pgdata


volumes:
  spring_adminlte_mysql_db:
  spring_adminlte_postgresql_db: